### ISSUE TITLE
neovim能用吗？

### ISSUE THREAD

**Issue by LichKing-W** [FittenTech/fittencode.vim#1]
neovim能用吗？不能的话之后会支持neovim嘛。

**Comment by lzhengning** [comment]
Vim 版刚刚更新了显示效果，NeoVim 也会很快支持

**Comment by lzhengning** [comment]
您好，已有开发者构建了 NeoVim 的 Fitten Code，可以参考该项目：

https://github.com/luozhiya/fittencode.nvim
