### ISSUE TITLE
我暂时没找见pycharm版本的，在这里提一个问题

### ISSUE THREAD

**Issue by LeeGongZi** [FittenTech/fittencode.vim#3]
这个工具生成python代码的时候经常会有拼写错误。一个特别离谱的是我定义了class之后按理来说要有init的函数，他自动生成的函数名叫__int__,一个字母之差我没看出来，后来找了半天错误发现的，希望看如何优化

**Comment by lzhengning** [comment]
谢谢您使用我们的工具，我们测试下来没有遇到同类的问题，可能是某些边界情况导致的，请问您能发一下具体的补全内容吗？

**Comment by LeeGongZi** [comment]
> 谢谢您使用我们的工具，我们测试下来没有遇到同类的问题，可能是某些边界情况导致的，请问您能发一下具体的补全内容吗？

感谢回复~

其实就是定义一个类之后出现的，后来我已经更正了。

比如这样
`class MyClass:`
在下面补全的时候：
补全成了类似
`    def __int__():`
这里init当时自动补全成了int，我需要的是init。
我刚才试类似的也是正常的。

**Comment by lzhengning** [comment]
谢谢您的回复，如果您遇到了类似的问题，可以记录相关或者截图发给我们，感谢您的反馈！
