### ISSUE TITLE
遇到‘TAB'制表符报错，有什么需要注意的事项吗？

### ISSUE THREAD

**Issue by mazhongguang** [FittenTech/fittencode.vim#6]
新建文件进行测试插件的功能，最前面几行生成代码正常，选择补全后，缩进里面含有’TAB'，两次使用<C+L>时就报错。手动将刚才补全的代码前面‘TAB'删除或者使用空格来替代缩进，则可以正常使用补全功能。

**Comment by lzhengning** [comment]
您好，已经更新了插件解决了这个问题，请您更新插件。谢谢您的反馈
